export const dataProducts = [
    {id: 1, name: 'iPhone 16 Pro Max', price: 49500, image: '/imageTopDeal/iphone 16.jpg', category: 'Điện thoại' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-18%', origin: 'Made in Apple', flashDown: 20},
    {id: 2, name: 'Áo thun Boston', price: 3100, image: '/imageTopDeal/ao thun1.jpg', category: 'Áo & Quần' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-21%', flashDown: 23},
    {id: 3, name: 'Macbook Pro 2019', price: 35100, image: '/imageTopDeal/macbook pro.jpg', category: 'Máy tính' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in USA', flashDown: 12},
    {id: 4, name: 'iPad Pro 2021', price: 3900, image: '/imageTopDeal/iPad pro.jpg', category: 'Máy tính bản' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in Japan', flashDown: 15},
    {id: 5, name: 'Giày Nike Air FG9K', price: 2900, image: '/imageTopDeal/shoes1.jpg', category: 'Giày' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4, origin: 'Made in UAE', flashDown: 25},
    {id: 6, name: 'Apple Watch SE 2023', price: 5600, image: '/imageTopDeal/apple watch1.jpg', category: 'Đồng hồ' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-19%', flashDown: 30},
    {id: 7, name: 'Macbook Pro 2019', price: 35100, image: '/imageTopDeal/macbook pro.jpg', category: 'Máy tính' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in Chile', flashDown: 29},
    {id: 8, name: 'Giày Nike Air FG9K', price: 2930, image: '/imageTopDeal/shoes1.jpg', category: 'Giày' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4, origin: 'Made in Qatar', flashDown: 22},
    {id: 9, name: 'Áo thun Boston', price: 3100, image: '/imageTopDeal/ao thun1.jpg', category: 'Áo & Quần' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-10%', flashDown: 32},
    {id: 10, name: 'iPad Pro 2021', price: 3900, image: '/imageTopDeal/iPad pro.jpg', category: 'Máy tính bản' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in Brazil', flashDown: 38},
    {id: 11, name: 'Macbook Pro 2019', price: 35100, image: '/imageTopDeal/macbook pro.jpg', category: 'Máy tính' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in Chile', flashDown: 27},
    {id: 12, name: 'Apple Watch SX 2024', price: 5640, image: '/imageTopDeal/apple watch1.jpg', category: 'Đồng hồ' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-18%', flashDown: 19},
    {id: 13, name: 'iPad Pro 2021', price: 3900, image: '/imageTopDeal/iPad pro.jpg', category: 'Máy tính bản' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4.5, origin: 'Made in Brazil', flashDown: 34},
    {id: 14, name: 'iPhone 16 Pro', price: 39500, image: '/imageTopDeal/iphone 16.jpg', category: 'Điện thoại' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-26%', origin: 'Made in Apple', flashDown: 28},
    {id: 15, name: 'Giày Nike Pro HJ8S', price: 2860, image: '/imageTopDeal/shoes1.jpg', category: 'Giày' , imgSP: '/imageTopDeal/imgFreeShipTop2.png', vote: 4, origin: 'Made in Qatar', flashDown: 24},
    {id: 16, name: 'Áo thun Boston', price: 2870, image: '/imageTopDeal/ao thun1.jpg', category: 'Áo & Quần' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-10%', flashDown: 33},
    {id: 17, name: 'iPhone 15 Pro Max', price: 30500, image: '/imageTopDeal/iphone 16.jpg', category: 'Điện thoại' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 4, phanTram:'-25%', origin: 'Made in Apple', flashDown: 36},
    {id: 18, name: 'Đồng hồ Orient SEL05005S0 Automatic', price: 1400, image: '/imageTopDeal/dongHo.png', category: 'Đồng hồ' , imgSP: '/imageTopDeal/imgFreeShipTop.png', vote: 5, phanTram:'-15%', origin: 'Made in Japan', flashDown: 22},
];

export const dataItemsBig = [
    {id: 1, name: 'Máy giặt Toshiba Inverter 10 Kg TW-T21BU110UWV(MG)', price: 8490, image: '/imgItemsBig/dt1.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in China', phanTram: '-30%', brand: 'APPLE'},
    {id: 2, name: 'Máy lọc nước Mutosi MP-P89K 9 lõi 3', price: 14600, image: '/imgItemsBig/dt2.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 4, origin: 'Made in Vietnam', phanTram: '-25%', brand: 'SAMSUNG'},
    {id: 3, name: 'Máy lọc nước Sunhouse UltraPURE 11 lõi', price: 6500, image: '/imgItemsBig/dt3.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in Indonesia', phanTram: '-35%', brand: 'OPPO'},
    {id: 4, name: 'Máy lọc nước Sunhouse UltraPURE 10 lõi', price: 4090, image: '/imgItemsBig/dt4.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 5, origin: 'Made in China', phanTram: '-20%', brand: 'APPLE'},
    {id: 5, name: 'Máy lọc nước RO Hòa Phát HPN666 11 lõi', price: 5990, image: '/imgItemsBig/dt5.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in USA', phanTram: '-30%', brand: 'APPLE'},
    {id: 6, name: 'Máy lọc nước Karofi KAD-X39 10 lõi', price: 7890, image: '/imgItemsBig/dt6.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-25%', brand: 'NIKE'},
    {id: 7, name: 'Máy lọc nước Karofi KAQ-U98 Pro 10 lõi', price: 6090, image: '/imgItemsBig/dt7.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 5, origin: 'Made in Indonesia', phanTram: '-19%', brand: 'ADIDAS'},
    {id: 8, name: 'Máy lọc nước Kangaroo KG116I 10 lõi', price: 4490, image: '/imgItemsBig/dt8.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 4, origin: 'Made in Bangladesh', phanTram: '-30%', brand: 'ZARA'},
    {id: 9, name: 'Máy lọc nước Karofi KAQ-X18 11 lõi', price: 5610, image: '/imgItemsBig/dt9.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4, origin: 'Made in India', phanTram: '-25%', brand: 'PORSCHE'},
    {id: 10, name: 'Máy lọc nước Karofi KAD-D66 11 lõi', price: 9900, image: '/imgItemsBig/dt10.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 5, origin: 'Made in USA', phanTram: '-40%', brand: 'HP'},
    {id: 11, name: 'Máy lọc nước Kangaroo KG12A8 12 lõi', price: 10990, image: '/imgItemsBig/dt11.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in China', phanTram: '-22%', brand: 'DELL'},
    {id: 12, name: 'Máy lọc nước Sunhouse SHA8810K 10 lõi', price: 4290, image: '/imgItemsBig/dt12.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 5, origin: 'Made in China', phanTram: '-28%', brand: 'APPLE'},
    {id: 13, name: 'Máy lọc nước Sunhouse SHA76210KL 10 lõi', price: 7690, image: '/imgItemsBig/dt13.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 4, origin: 'Made in Vietnam', phanTram: '-19%', brand: 'OPPO'},
    {id: 14, name: 'Máy lọc nước Karofi KAD-X58 11 lõi', price: 11140, image: '/imgItemsBig/dt14.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-30%', brand: 'SAMSUNG'},
    {id: 15, name: 'Máy lọc nước Toshiba TWP-W2398SVN 10 lõi', price: 13140, image: '/imgItemsBig/dt15.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lọc nước', vote: 5, origin: 'Made in China', phanTram: '-35%', brand: 'APPLE'},
    {id: 16, name: 'Máy lọc nước Mutosi MP-S1021H 10 lõi', price: 8990, image: '/imgItemsBig/dt16.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 4, origin: 'Made in China', phanTram: '-25%', brand: 'XIAOMI'},
    {id: 17, name: 'Máy lọc nước Livotec 638 10 lõi', price: 7590, image: '/imgItemsBig/dt17.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lọc nước', vote: 4.5, origin: 'Made in USA', phanTram: '-20%', brand: 'APPLE'},
    {id: 18, name: 'Nồi cơm điện tử BlueStone 1.5 lít RCB-5946', price: 1290, image: '/imgItemsBig/dt18.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in Korea', phanTram: '-28%', brand: 'SAMSUNG'},
    {id: 19, name: 'Nồi cơm điện tử Electrolux 1 lít E7RC1-550K', price: 1490, image: '/imgItemsBig/dt19.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Indonesia', phanTram: '-30%', brand: 'OPPO'},
    {id: 20, name: 'Nồi cơm điện tử Sunhouse 1.8 lít SHD8911', price: 1290, image: '/imgItemsBig/dt20.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in China', phanTram: '-22%', brand: 'APPLE'},
    {id: 21, name: 'Nồi cơm điện tử Cuckoo 1.8 lít CR-1020F', price: 1690, image: '/imgItemsBig/dt21.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-25%', brand: 'SAMSUNG'},
    {id: 22, name: 'Nồi cơm điện tử Kangaroo 1.5 lít KG15DR10', price: 1390, image: '/imgItemsBig/dt22.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in Vietnam', phanTram: '-19%', brand: 'NIKE'},
    {id: 23, name: 'Nồi cơm điện tử Kangaroo 1.8 lít KG18DR8', price: 1490, image: '/imgItemsBig/dt23.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Japan', phanTram: '-35%', brand: 'ASICS'},
    {id: 24, name: 'Nồi cơm điện tử BlueStone 1.8 lít RCB-5938', price: 1480, image: '/imgItemsBig/dt24.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 4, origin: 'Made in Bangladesh', phanTram: '-22%', brand: "LEVI'S"},
    {id: 25, name: 'Nồi cơm điện tử Philips 1.8 lít HD4515/55', price: 1590, image: '/imgItemsBig/dt25.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-27%', brand: 'NY'},
    {id: 26, name: 'Nồi cơm điện tử Sharp 1.8 lít KS-COM194EV-BK', price: 1890, image: '/imgItemsBig/dt26.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in China', phanTram: '-40%', brand: 'LENOVO'},
    {id: 27, name: 'Nồi cơm điện tử Sunhouse mama 1.8 lít SHD8903', price: 1790, image: '/imgItemsBig/dt27.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in China', phanTram: '-32%', brand: 'APPLE'},
    {id: 28, name: 'Nồi cơm điện tử Tefal 1.8 lít RK737868', price: 1890, image: '/imgItemsBig/dt28.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-27%', brand: 'GOOGLE'},
    {id: 29, name: 'Nồi cơm điện tử BlueStone 1.5 lít RCB-5988', price: 2290, image: '/imgItemsBig/dt29.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-22%', brand: 'OPPO'},
    {id: 30, name: 'Nồi cơm điện cao tần Sunhouse 1.5 lít SHD8955', price: 2317, image: '/imgItemsBig/dt30.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 4, origin: 'Made in China', phanTram: '-30%', brand: 'APPLE'},
    {id: 31, name: 'Nồi cơm điện cao tần Tefal 1.5 lít RK808168', price: 1990, image: '/imgItemsBig/dt31.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in Vietnam', phanTram: '-28%', brand: 'SAMSUNG'},
    {id: 32, name: 'Nồi cơm điện tử Toshiba 1.8 lít RC-18NMFVN(WT)', price: 3050, image: '/imgItemsBig/dt32.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 4.5, origin: 'Made in China', phanTram: '-33%', brand: 'APPLE'},
    {id: 33, name: 'Nồi cơm điện cao tần Midea 1.5 lít MB-HS4007', price: 2770, image: '/imgItemsBig/dt33.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi cơm điện', vote: 5, origin: 'Made in USA', phanTram: '-19%', brand: 'APPLE'},
    {id: 34, name: 'Bếp từ hồng ngoại lắp âm Junger SIS-66', price: 10190, image: '/imgItemsBig/dt34.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in Korea', phanTram: '-22%', brand: 'SAMSUNG'},
    {id: 35, name: 'Bếp từ đôi lắp âm Junger MK-22', price: 12590, image: '/imgItemsBig/dt35.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in Indonesia', phanTram: '-30%', brand: 'OPPO'},
    {id: 36, name: 'Bếp từ hồng ngoại lắp âm BlueStone ICB-6911', price: 4990, image: '/imgItemsBig/dt36.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 5, origin: 'Made in Japan', phanTram: '-40%', brand: 'SONY'},
    {id: 37, name: 'Bếp từ đôi lắp âm Hafele HC-I2712A', price: 7290, image: '/imgItemsBig/dt37.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-30%', brand: 'NIKE'},
    {id: 38, name: 'Bếp từ đôi lắp âm Rapido RI4000DS', price: 3590, image: '/imgItemsBig/dt38.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 5, origin: 'Made in Indonesia', phanTram: '-19%', brand: 'ADIDAS'},
    {id: 39, name: 'Bếp từ đôi lắp âm Pramie PRTH-2203', price: 7590, image: '/imgItemsBig/dt39.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in India', phanTram: '-22%', brand: 'Vietnam'},
    {id: 40, name: 'Bếp từ đôi lắp âm Sunhouse SHB9111MT', price: 2790, image: '/imgItemsBig/dt40.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 5, origin: 'Made in Bangladesh', phanTram: '-28%', brand: "LEVI'S"},
    {id: 41, name: 'Bếp từ đôi lắp âm Pramie PRTH-A2', price: 6590, image: '/imgItemsBig/dt41.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 5, origin: 'Made in China', phanTram: '-30%', brand: 'APPLE'},
    {id: 42, name: 'Bếp từ đôi lắp âm Hafele HC-I2732A', price: 12190, image: '/imgItemsBig/dt42.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 5, origin: 'Made in Taiwan', phanTram: '-35%', brand: 'ASUS'},
    {id: 43, name: 'Bếp từ đôi lắp âm Sunhouse SHB82082-VMD', price: 5390, image: '/imgItemsBig/dt43.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in China', phanTram: '-25%', brand: 'ACER'},
    {id: 44, name: 'Bếp từ đôi lắp âm BlueStone ICB-6821', price: 4490, image: '/imgItemsBig/dt44.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 4, origin: 'Made in Korea', phanTram: '-22%', brand: 'SAMSUNG'},
    {id: 45, name: 'Bếp từ đôi lắp âm Junger CEJ-200-II', price: 20290, image: '/imgItemsBig/dt45.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in Indonesia', phanTram: '-19%', brand: 'OPPO'},
    {id: 46, name: 'Bếp từ Sunhouse SHD6805', price: 1090, image: '/imgItemsBig/dt46.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 4.5, origin: 'Made in China', phanTram: '-25%', brand: 'APPLE'},
    {id: 47, name: 'Bếp từ Electrolux ETD29MKC', price: 1540, image: '/imgItemsBig/dt47.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 5, origin: 'Made in Vietnam', phanTram: '-30%', brand: 'OPPO'},
    {id: 48, name: 'Bếp từ Pramie PRMY-1109', price: 1290, image: '/imgItemsBig/dt48.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Bếp từ', vote: 4, origin: 'Made in Vietnam', phanTram: '-28%', brand: 'XIAOMI'},
    {id: 49, name: 'Bếp từ Pramie PRMY-1102', price: 1390, image: '/imgItemsBig/dt49.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Bếp từ', vote: 4, origin: 'Made in Vietnam', phanTram: '-22%', brand: 'OPPO'},
    {id: 50, name: 'Máy lạnh 2 chiều Daikin Inverter 1 HP', price: 12590, image: '/imgItemsBig/dt50.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in China', phanTram: '-35%', brand: 'HUAWEI'},
    {id: 51, name: 'Máy lạnh Daikin Inverter 1 HP FTKY25WMVMV', price: 12490, image: '/imgItemsBig/dt51.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 4, origin: 'Made in China', phanTram: '-22%', brand: 'DELL'},
    {id: 52, name: 'Máy lạnh Panasonic Inverter HP CU/CS-PU12AKH-8', price: 14290, image: '/imgItemsBig/dt52.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in China', phanTram: '-27%', brand: 'LENOVO'},
    {id: 53, name: 'Máy lạnh Samsung Inverter 1.5 HP AR13DYHZAWKNSV', price: 10490, image: '/imgItemsBig/dt53.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 5, origin: 'Made in Vietnam', phanTram: '-35%', brand: 'eBook'},
    {id: 54, name: 'Máy lạnh Midea Inverter 1 HP MSAGA-10CRDN8', price: 7090, image: '/imgItemsBig/dt54.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in India', phanTram: '-36%', brand: 'eBook'},
    {id: 55, name: 'Máy lạnh Toshiba Inverter 1.5 HP RAS-H13Z1KCVG-V', price: 12490, image: '/imgItemsBig/dt55.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4, origin: 'Made in China', phanTram: '-20%', brand: 'APPLE'},
    {id: 56, name: 'Máy lạnh Sharp Inverter 1.5 HP AH-X13ZEW', price: 10540, image: '/imgItemsBig/dt56.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 5, origin: 'Made in Vietnam', phanTram: '-38%', brand: 'SAMSUNG'},
    {id: 57, name: 'Máy lạnh LG Inverter 2 HP V18WIN1', price: 17490, image: '/imgItemsBig/dt57.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 5, origin: 'Made in Vietnam', phanTram: '-30%', brand: 'GOOGLE'},
    {id: 58, name: 'Tủ đông Kangaroo 327 lít KG498KX2', price: 8490, image: '/imgItemsBig/dt58.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in USA', phanTram: '-32%', brand: 'MICROSOFT'},
    {id: 59, name: 'Tủ đông Hòa Phát 245 Lít HPF BD6245', price: 5590, image: '/imgItemsBig/dt59.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4, origin: 'Made in Indonesia', phanTram: '-30%', brand: 'eBook'},
    {id: 60, name: 'Tủ đông Kangaroo 90 lít KG090C1N', price: 3690, image: '/imgItemsBig/dt60.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in China', phanTram: '-27%', brand: 'BALENCIAGA'},
    {id: 61, name: 'Tủ đông Sanaky 220 lít VH-2899W1', price: 5790, image: '/imgItemsBig/dt61.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4, origin: 'Made in Italy', phanTram: '-40%', brand: 'LOUIS VUITTON'},
    {id: 62, name: 'Tủ đông SANAKY 208 Lít TD.VH255HY2', price: 4790, image: '/imgItemsBig/dt62.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 5, origin: 'Made in USA', phanTram: '-30%', brand: 'BOSE'},
    {id: 63, name: 'Tủ đông Sanaky 100 lít VH162HY2', price: 3690, image: '/imgItemsBig/dt63.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4, origin: 'Made in China', phanTram: '-25%', brand: 'MSI'},
    {id: 64, name: 'Tủ đông Hòa Phát 107 lít HPF AN6107', price: 3590, image: '/imgItemsBig/dt64.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4, origin: 'Made in Vietnam', phanTram: '-22%', brand: 'GUCCI'},
    {id: 65, name: 'Tủ đông Hòa Phát 352 Lít HPF AD6352', price: 6690, image: '/imgItemsBig/dt65.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in Indonesia', phanTram: '-30%', brand: 'CHANEL'},
    {id: 66, name: 'Tủ đông đứng Hòa Phát 147 Lít HPF UAH6147', price: 4490, image: '/imgItemsBig/dt66.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in China', phanTram: '-35%', brand: 'eBook'},
    {id: 67, name: 'Tủ đông Kangaroo Inverter 430 lít KGFZ490IG1', price: 11390, image: '/imgItemsBig/dt67.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-22%', brand: 'LACOSTE'},
    {id: 68, name: 'Tủ đông Sanaky Inverter 761 lít VH-8699HY3', price: 18790, image: '/imgItemsBig/dt68.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in China', phanTram: '-30%', brand: 'DOLCE'},
    {id: 69, name: 'Tủ đông Sanaky 485 lít VH-6699W1', price: 14390, image: '/imgItemsBig/dt69.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 5, origin: 'Made in Taiwan', phanTram: '-40%', brand: 'ASUS'},
    {id: 70, name: 'Tủ đông Sanaky 500 lít VH-888KA', price: 17390, image: '/imgItemsBig/dt70.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 5, origin: 'Made in China', phanTram: '-33%', brand: 'APPLE'},
    {id: 71, name: 'Tủ đông Hòa Phát 783 lít HPF AD6783', price: 12490, image: '/imgItemsBig/dt71.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in USA', phanTram: '-30%', brand: 'eBook'},
    {id: 72, name: 'Tủ đông Sanaky Inverter 1143.5 lít VH-1399HY3', price: 31790, image: '/imgItemsBig/dt72.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ đông', vote: 4.5, origin: 'Made in Israel', phanTram: '-28%', brand: 'eBook'},
    {id: 73, name: 'Nồi chiên không dầu Rapido RAF5.0M 5 lít', price: 990, image: '/imgItemsBig/dt73.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in USA', phanTram: '-28%', brand: 'NIKE'},
    {id: 74, name: 'Nồi chiên không dầu Electrolux E6AF1-220K 3 lít', price: 1090, image: '/imgItemsBig/dt74.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in Israel', phanTram: '-28%', brand: 'VERSACE'},
    {id: 75, name: 'Nồi chiên không dầu AVA 55K07A 5.5 lít', price: 990, image: '/imgItemsBig/dt75.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 5, origin: 'Made in USA', phanTram: '-33%', brand: 'eBook'},
    {id: 76, name: 'Nồi chiên không dầu Dreamer DF-S40B 3.5 lít', price: 909, image: '/imgItemsBig/dt76.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 5, origin: 'Made in UK', phanTram: '-33%', brand: 'FRANCHI'},
    {id: 77, name: 'Lò chiên không dầu Rapido RAF-12M1 12 lít', price: 1350, image: '/imgItemsBig/dt77.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in Vietnam', phanTram: '-29%', brand: 'eBook'},
    {id: 78, name: 'Nồi chiên không dầu Mutosi MF-T891 12 lít', price: 1290, image: '/imgItemsBig/dt78.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in France', phanTram: '-32%', brand: 'FRFANCHI'},
    {id: 79, name: 'Nồi chiên không dầu Bear QZG-A15T2 4.5 lít', price: 1090, image: '/imgItemsBig/dt79.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in France', phanTram: '-32%', brand: 'MAJE'},
    {id: 80, name: 'Nồi chiên không dầu Ferroli FAF-5.0M3 5 lít', price: 1290, image: '/imgItemsBig/dt80.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in Japan', phanTram: '-38%', brand: 'eBook'},
    {id: 81, name: 'Lò chiên không dầu Ferroli FAF-12M 12 lít', price: 1790, image: '/imgItemsBig/dt81.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in Canada', phanTram: '-34%', brand: 'eBook'},
    {id: 82, name: 'Nồi chiên không dầu Rapido RAF-7.5M3 7.5 lít', price: 1390, image: '/imgItemsBig/dt82.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in India', phanTram: '-36%', brand: 'XIAOMI'},
    {id: 83, name: 'Nồi chiên không dầu AVA AF40155D 5 lít', price: 990, image: '/imgItemsBig/dt83.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in China', phanTram: '-30%', brand: 'REALME'},
    {id: 84, name: 'Nồi chiên không dầu Philips NA130/00 6.2 lít', price: 1790, image: '/imgItemsBig/dt84.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in Japan', phanTram: '-35%', brand: 'VN'},
    {id: 85, name: 'Nồi chiên không dầu Bear BAF-P63W1 6 lít', price: 1550, image: '/imgItemsBig/dt85.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in Vietnam', phanTram: '-40%', brand: 'eBook'},
    {id: 86, name: 'Nồi chiên không dầu Sunhouse SHD4035 9 lít', price: 2070, image: '/imgItemsBig/dt86.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4, origin: 'Made in Đức', phanTram: '-40%', brand: 'ADIDAS'},
    {id: 87, name: 'Nồi chiên không dầu Sunhouse SHD4026 6 lít', price: 1690, image: '/imgItemsBig/dt87.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Nồi chiên không dầu', vote: 4.5, origin: 'Made in Brazil', phanTram: '-30%', brand: 'eBook'},
    {id: 88, name: 'Máy nước nóng trực tiếp Rapido SONNE - SN4.5', price: 1090, image: '/imgItemsBig/dt88.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in Brazil', phanTram: '-30%', brand: 'MAJE'},
    {id: 89, name: 'Máy nước nóng trực tiếp Ariston AURES PREMIUM 4.5P PEARL', price: 3090, image: '/imgItemsBig/dt89.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in Italy', phanTram: '-25%', brand: 'GUCCI'},
    {id: 90, name: 'Máy nước nóng trực tiếp Ferroli MIDO-MSP 4.5S', price: 2690, image: '/imgItemsBig/dt90.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 4, origin: 'Made in USA', phanTram: '-30%', brand: 'ALLEN EDMONDS'},
    {id: 91, name: 'Máy nước nóng trực tiếp Panasonic DH-4VS1VW', price: 2990, image: '/imgItemsBig/dt91.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in Spain', phanTram: '-35%', brand: 'SANTONI'},
    {id: 92, name: 'Máy nước nóng trực tiếp Ariston AURES PREMIUM+ 4.5P', price: 3690, image: '/imgItemsBig/dt92.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 5, origin: 'Made in Italy', phanTram: '-20%', brand: 'SALVATORE FERRAGAMO'},
    {id: 93, name: 'Máy nước nóng trực tiếp Electrolux EWE451QB-W4', price: 3490, image: '/imgItemsBig/dt93.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4, origin: 'Made in UK', phanTram: '-22%', brand: 'CHURCH\'S'},
    {id: 94, name: 'Máy nước nóng gián tiếp Ferroli 20 lít MIDO-DE', price: 2890, image: '/imgItemsBig/dt94.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 5, origin: 'Made in France', phanTram: '-30%', brand: 'CHANEL'},
    {id: 95, name: 'Máy nước nóng gián tiếp Kangaroo 22 lít KG68A2', price: 2990, image: '/imgItemsBig/dt95.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in France', phanTram: '-28%', brand: 'LOUIS VUITTON'},
    {id: 96, name: 'Máy nước nóng gián tiếp Rapido 20 lít HE 20L', price: 1690, image: '/imgItemsBig/dt96.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy nước nóng', vote: 4, origin: 'Made in Italy', phanTram: '-19%', brand: 'GUCCI'},
    {id: 97, name: 'Máy nước nóng gián tiếp Ariston 20 lít VITALY 20 SLIM 2.5', price: 1990, image: '/imgItemsBig/dt97.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in Italy', phanTram: '-35%', brand: 'PRADA'},
    {id: 98, name: 'Máy nước nóng nóng gián tiếp Ferroli 20 lít MIDO SQ', price: 2490, image: '/imgItemsBig/dt98.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 5, origin: 'Made in France', phanTram: '-40%', brand: 'HERMÈS'},
    {id: 99, name: 'Máy nước nóng gián tiếp Atlantic 20 lít SWH 20H M-14 ESA', price: 1890, image: '/imgItemsBig/dt99.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 5, origin: 'Made in Korea', phanTram: '-25%', brand: 'Samsung'},
    {id: 100, name: 'Máy giặt Direct Drive JO-243', price: 8390, image: '/imgItemsBig/dt100.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Korea', phanTram: '-40%', brand: 'LG'},
    {id: 101, name: 'Máy nước nóng trực tiếp Ferroli MIDO-MSN 4.5S', price: 1690, image: '/imgItemsBig/dt101.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 5, origin: 'Made in China', phanTram: '-21%', brand: 'Apple'},
    {id: 102, name: 'Máy Giặt Samsung FlexWash', price: 7990, image: '/imgItemsBig/dt102.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 4, origin: 'Made in Korea', phanTram: '-35%', brand: 'Samsung'},
    {id: 103, name: 'Máy nước nóng gián tiếp Ariston 15 lít AN2 RS 2.5', price: 3290, image: '/imgItemsBig/dt103.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy nước nóng', vote: 4.5, origin: 'Made in China', phanTram: '-30%', brand: 'Microsoft'},
    {id: 104, name: 'Máy Giặt Bosch Serie 8', price: 8790, image: '/imgItemsBig/dt104.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Germany', phanTram: '-45%', brand: 'Bosch'},
    {id: 105, name: 'Máy sấy thông hơi Casper 7.2 Kg TD-72VWD', price: 5490, image: '/imgItemsBig/dt105.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy sấy', vote: 4, origin: 'Made in China', phanTram: '-22%', brand: 'Xiaomi'},
    {id: 106, name: 'Máy Giặt Electrolux EWF12933', price: 8890, image: '/imgItemsBig/dt106.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 5, origin: 'Made in Thailand', phanTram: '-40%', brand: 'Electrolux'},
    {id: 107, name: 'Máy sấy thông hơi Toshiba 7 Kg TD-H80SEV(SK)', price: 1600, image: '/imgItemsBig/dt107.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy sấy', vote: 4, origin: 'Made in China', phanTram: '-30%', brand: 'Lenovo'},
    {id: 108, name: 'Máy giặt Toshiba Inverter 9.5kg', price: 7790, image: '/imgItemsBig/dt108.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in USA', phanTram: '-28%', brand: 'Whirlpool'},
    {id: 109, name: 'Máy sấy thông hơi Aqua 7 Kg AQH-V700FW', price: 5490, image: '/imgItemsBig/dt109.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4.5, origin: 'Made in Korea', phanTram: '-33%', brand: 'Samsung'},
    {id: 110, name: 'Máy Giặt Miele W1', price: 5600, image: '/imgItemsBig/dt110.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 5, origin: 'Made in Germany', phanTram: '-45%', brand: 'Miele'},
    {id: 111, name: 'Máy sấy bơm nhiệt Samsung 9 Kg DV90T7240BB/SV', price: 21990, image: '/imgItemsBig/dt111.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy sấy', vote: 5, origin: 'Made in China', phanTram: '-21%', brand: 'Apple'},
    {id: 112, name: 'Máy Giặt Toshiba TW-BJ80A4', price: 10100, image: '/imgItemsBig/dt112.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4, origin: 'Made in Japan', phanTram: '-32%', brand: 'Toshiba'},
    {id: 113, name: 'Máy sấy thông hơi Electrolux 8.5 Kg EDV854J3WB', price: 8990, image: '/imgItemsBig/dt113.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4, origin: 'Made in India', phanTram: '-27%', brand: 'Realme'},
    {id: 114, name: 'Máy Giặt Bosch Serie 6', price: 10310, image: '/imgItemsBig/dt114.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 4, origin: 'Made in Germany', phanTram: '-36%', brand: 'Bosch'},
    {id: 115, name: 'Máy sấy bơm nhiệt LG 10.5 Kg DVHP50B', price: 19890, image: '/imgItemsBig/dt115.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4.5, origin: 'Made in China', phanTram: '-32%', brand: 'Huawei'},
    {id: 116, name: 'Máy Giặt Samsung AddWash 9 kg', price: 7400, image: '/imgItemsBig/dt116.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 5, origin: 'Made in Korea', phanTram: '-41%', brand: 'Samsung'},
    {id: 117, name: 'Máy sấy bơm nhiệt LG 10.5 Kg DVHP50P', price: 19340, image: '/imgItemsBig/dt117.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4, origin: 'Made in China', phanTram: '-26%', brand: 'Acer'},
    {id: 118, name: 'Máy Giặt Hitachi SF-90M', price: 9080, image: '/imgItemsBig/dt118.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Japan', phanTram: '-30%', brand: 'Hitachi'},
    {id: 119, name: 'Máy sấy ngưng tụ Toshiba 8 Kg TD-K90MEV(SK)', price: 9990, image: '/imgItemsBig/dt119.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4, origin: 'Made in China', phanTram: '-25%', brand: 'Xiaomi'},
    {id: 120, name: 'Máy Giặt Panasonic NA-F70A1', price: 9800, image: '/imgItemsBig/dt120.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Japan', phanTram: '-38%', brand: 'Panasonic'},
    {id: 121, name: 'Máy Giặt LG TWINWash Mini', price: 7890, image: '/imgItemsBig/dt121.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Korea', phanTram: '-31%', brand: 'LG'},
    {id: 122, name: 'Máy lạnh Panasonic CS-PU9TKH-8', price: 9780, image: '/imgItemsBig/dt122.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-28%', brand: 'Panasonic'},
    {id: 123, name: 'Máy lạnh Mitsubishi Heavy SRK50ZSA-S', price: 11100, image: '/imgItemsBig/dt123.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in Thailand', phanTram: '-33%', brand: 'Mitsubishi'},
    {id: 124, name: 'Máy lạnh Samsung AR12TYHQASIN', price: 8040, image: '/imgItemsBig/dt124.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 5, origin: 'Made in Korea', phanTram: '-27%', brand: 'Samsung'},
    {id: 125, name: 'Máy lạnh LG V18ENF', price: 7900, image: '/imgItemsBig/dt125.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4, origin: 'Made in Korea', phanTram: '-32%', brand: 'LG'},
    {id: 126, name: 'Máy lạnh Toshiba RAS-H10C2KCVG-V', price: 9560, image: '/imgItemsBig/dt126.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in Japan', phanTram: '-29%', brand: 'Toshiba'},
    {id: 127, name: 'Máy lạnh Hitachi RAS-R10C2', price: 6700, image: '/imgItemsBig/dt127.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Máy lạnh', vote: 4, origin: 'Made in Japan', phanTram: '-25%', brand: 'Hitachi'},
    {id: 128, name: 'Máy lạnh Sharp AH-X9SEW', price: 7600, image: '/imgItemsBig/dt128.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-30%', brand: 'Sharp'},
    {id: 129, name: 'Tủ lạnh Panasonic NR-BV320QSVN', price: 8900, image: '/imgItemsBig/dt129.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ lạnh', vote: 5, origin: 'Made in Malaysia', phanTram: '-35%', brand: 'Panasonic'},
    {id: 130, name: 'Tủ lạnh Samsung RT32K5032S8', price: 7880, image: '/imgItemsBig/dt130.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Korea', phanTram: '-28%', brand: 'Samsung'},
    {id: 131, name: 'Tủ lạnh LG GN-B562PL', price: 9800, image: '/imgItemsBig/dt131.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ lạnh', vote: 5, origin: 'Made in Korea', phanTram: '-40%', brand: 'LG'},
    {id: 132, name: 'Tủ lạnh Electrolux ETB4500AA', price: 7890, image: '/imgItemsBig/dt132.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Thailand', phanTram: '-33%', brand: 'Electrolux'},
    {id: 133, name: 'Tủ lạnh Toshiba GR-RB34VPDZ', price: 9870, image: '/imgItemsBig/dt133.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ lạnh', vote: 5, origin: 'Made in Japan', phanTram: '-35%', brand: 'Toshiba'},
    {id: 134, name: 'Tủ lạnh Beko RCSA290K30V', price: 8690, image: '/imgItemsBig/dt134.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4, origin: 'Made in Turkey', phanTram: '-30%', brand: 'Beko'},
    {id: 135, name: 'Tủ lạnh Sharp SJ-X231E', price: 8170, image: '/imgItemsBig/dt135.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Sharp'},
    {id: 136, name: 'Tủ lạnh Samsung RT29K5032S8', price: 9100, image: '/imgItemsBig/dt136.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 5, origin: 'Made in Korea', phanTram: '-28%', brand: 'Samsung'},
    {id: 137, name: 'Tủ lạnh Mitsubishi MR-WX60Y', price: 7200, image: '/imgItemsBig/dt137.png', imgSP: '/imageTopDeal/imgFreeShipTop2.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Japan', phanTram: '-36%', brand: 'Mitsubishi'},
    {id: 138, name: 'Tủ lạnh Panasonic NR-BV290QSVN', price: 9230, image: '/imgItemsBig/dt138.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 139, name: 'Máy sấy thông hơi Aqua 8 Kg AQH-V800H SS', price: 6490, image: '/imgItemsBig/dt139.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 140, name: 'Máy sấy thông hơi Galanz 7 Kg DV-70T5C(W)', price: 3990, image: '/imgItemsBig/dt140.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 141, name: 'Máy sấy thông hơi Beko 8 Kg DA8112RX0W', price: 4990, image: '/imgItemsBig/dt141.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 142, name: 'Máy sấy bơm nhiệt Samsung 9 Kg DV90BB9440GH/SV', price: 20990, image: '/imgItemsBig/dt142.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 143, name: 'Máy sấy thông hơi Whirlpool 7 Kg AWD712S2', price: 4910, image: '/imgItemsBig/dt143.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 144, name: 'Máy sấy bơm nhiệt Panasonic 9.5 Kg NH-EH95JD1BV', price: 22990, image: '/imgItemsBig/dt144.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 145, name: 'Máy sấy bơm nhiệt Hitachi 10 Kg TD-100XFVEM', price: 23560, image: '/imgItemsBig/dt145.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy sấy', vote: 5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 146, name: 'Tủ lạnh Toshiba Inverter 180 lít GR-B22VU UKG', price: 5190, image: '/imgItemsBig/dt146.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 147, name: 'Tủ lạnh Panasonic Inverter 405 lít NR-TX461GPKV', price: 14590, image: '/imgItemsBig/dt147.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 148, name: 'Tủ lạnh Aqua Inverter 646 lít AQR-S682XA(SLB)', price: 16790, image: '/imgItemsBig/dt148.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 149, name: 'Tủ lạnh Toshiba 474 lít GR-RF611WI-PGV(22)-XK', price: 16990, image: '/imgItemsBig/dt149.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 150, name: 'Tủ lạnh LG Inverter 519 lít GR-B256JDS', price: 12490, image: '/imgItemsBig/dt150.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Tủ lạnh', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 151, name: 'Máy giặt Samsung Inverter 10 Kg WW10TP44DSB/SV', price: 12390, image: '/imgItemsBig/dt151.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
    {id: 152, name: 'Máy giặt LG Inverter 12 Kg FV1412S4W', price: 12190, image: '/imgItemsBig/dt152.png', imgSP: '/imageTopDeal/imgFreeShipTop.png', category: 'Máy giặt', vote: 4.5, origin: 'Made in Malaysia', phanTram: '-32%', brand: 'Panasonic'},
];

export const dataImgCategory = [
  {id: 1, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate1.png'},
  {id: 2, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate2.png'},
  {id: 3, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate3.png'},
  {id: 4, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate4.png'},
  {id: 5, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate5.png'},
  {id: 6, category: 'Tủ lạnh', image: '/imageSliderCategory/imgCate6.png'},
  {id: 7, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate7.png'},
  {id: 8, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate8.png'},
  {id: 9, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate9.png'},
  {id: 10, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate10.png'},
  {id: 11, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate11.png'},
  {id: 12, category: 'Máy lọc nước', image: '/imageSliderCategory/imgCate12.png'},
  {id: 13, category: 'Máy giặt', image: '/imageSliderCategory/imgCate13.png'},
  {id: 14, category: 'Máy giặt', image: '/imageSliderCategory/imgCate14.png'},
  {id: 15, category: 'Máy giặt', image: '/imageSliderCategory/imgCate15.png'},
  {id: 16, category: 'Máy giặt', image: '/imageSliderCategory/imgCate16.png'},
  {id: 17, category: 'Máy giặt', image: '/imageSliderCategory/imgCate17.png'},
  {id: 18, category: 'Máy giặt', image: '/imageSliderCategory/imgCate18.png'},
  {id: 19, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate19.png'},
  {id: 20, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate20.png'},
  {id: 21, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate21.png'},
  {id: 22, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate22.png'},
  {id: 23, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate23.png'},
  {id: 24, category: 'Nồi cơm điện', image: '/imageSliderCategory/imgCate24.png'},
  {id: 25, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate25.png'},
  {id: 26, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate26.png'},
  {id: 27, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate27.png'},
  {id: 28, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate28.png'},
  {id: 29, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate29.png'},
  {id: 30, category: 'Máy lạnh', image: '/imageSliderCategory/imgCate30.png'},
  {id: 31, category: 'Bếp từ', image: '/imageSliderCategory/imgCate31.png'},
  {id: 32, category: 'Bếp từ', image: '/imageSliderCategory/imgCate32.png'},
  {id: 33, category: 'Bếp từ', image: '/imageSliderCategory/imgCate33.png'},
  {id: 34, category: 'Bếp từ', image: '/imageSliderCategory/imgCate34.png'},
  {id: 35, category: 'Bếp từ', image: '/imageSliderCategory/imgCate35.png'},
  {id: 36, category: 'Bếp từ', image: '/imageSliderCategory/imgCate36.png'},
  {id: 37, category: 'Tủ đông', image: '/imageSliderCategory/imgCate37.png'},
  {id: 38, category: 'Tủ đông', image: '/imageSliderCategory/imgCate38.png'},
  {id: 39, category: 'Tủ đông', image: '/imageSliderCategory/imgCate39.png'},
  {id: 40, category: 'Tủ đông', image: '/imageSliderCategory/imgCate40.png'},
  {id: 41, category: 'Tủ đông', image: '/imageSliderCategory/imgCate41.png'},
  {id: 42, category: 'Tủ đông', image: '/imageSliderCategory/imgCate42.png'},
  {id: 43, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate43.png'},
  {id: 44, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate44.png'},
  {id: 45, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate45.png'},
  {id: 46, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate46.png'},
  {id: 47, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate47.png'},
  {id: 48, category: 'Nồi chiên không dầu', image: '/imageSliderCategory/imgCate48.png'},
  {id: 49, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate49.png'},
  {id: 50, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate50.png'},
  {id: 51, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate51.png'},
  {id: 52, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate52.png'},
  {id: 53, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate53.png'},
  {id: 54, category: 'Máy nước nóng', image: '/imageSliderCategory/imgCate54.png'},
  {id: 55, category: 'Máy sấy', image: '/imageSliderCategory/imgCate55.png'},
  {id: 56, category: 'Máy sấy', image: '/imageSliderCategory/imgCate56.png'},
  {id: 57, category: 'Máy sấy', image: '/imageSliderCategory/imgCate57.png'},
  {id: 58, category: 'Máy sấy', image: '/imageSliderCategory/imgCate58.png'},
  {id: 59, category: 'Máy sấy', image: '/imageSliderCategory/imgCate59.png'},
  {id: 60, category: 'Máy sấy', image: '/imageSliderCategory/imgCate60.png'},
]

export const dataCategory = [
  {id: 1, name: 'Máy giặt', img: '/imageDanhMuc/dm1.png', path: 'may-giat'},
  {id: 2, name: 'Máy lọc nước', img: '/imageDanhMuc/dm2.png', path: 'may-loc-nuoc'},
  {id: 3, name: 'Tủ lạnh', img: '/imageDanhMuc/dm3.png', path: 'tu-lanh'},
  {id: 4, name: 'Nồi cơm điện', img: '/imageDanhMuc/dm4.png', path: 'noi-com-dien'},
  {id: 5, name: 'Máy lạnh', img: '/imageDanhMuc/dm5.png', path: 'may-lanh'},
  {id: 6, name: 'Bếp từ', img: '/imageDanhMuc/dm6.png', path: 'bep-tu'},
  {id: 7, name: 'Tủ đông', img: '/imageDanhMuc/dm7.png', path: 'tu-dong'},
  {id: 8, name: 'Nồi chiên không dầu', img: '/imageDanhMuc/dm8.png', path: 'noi-chien-khong-dau'},
  {id: 9, name: 'Máy nước nóng', img: '/imageDanhMuc/dm9.png', path: 'may-nuoc-nong'},
  {id: 10, name: 'Máy sấy quần áo', img: '/imageDanhMuc/dm10.png', path: 'may-say'},
]

export const categorys = ['Tất cả',
  'Máy giặt',
  'Máy lọc nước',
  'Tủ lạnh',
  'Nồi cơm điện',
  'Máy lạnh',
  'Bếp từ',
  'Tủ đông',
  'Nồi chiên không dầu',
  'Máy nước nóng',
  'Máy sấy quần áo'
]

export const dataImgCarousel = [
    {img: '/imageHome/images/carousel1.png'},
    {img: '/imageHome/images/carousel2.png'},
    {img: '/imageHome/images/carousel3.png'},
    {img: '/imageHome/images/carousel4.png'},
    {img: '/imageHome/images/carousel5.png'},
    {img: '/imageHome/images/carousel6.png'},
];

export const settings = {
    dots: true,
    infinite: true,
    slidesToShow: 2,
    slidesToScroll: 2,
    autoplay: true,
    autoplaySpeed: 3000,
};

export const settings2 = {
    dots: true,
    infinite: true,
    speed: 700,
    slidesToShow: 6,
    slidesToScroll: 6,
};

export const settings3 = {
    dots: true,
    infinite: true,
    speed: 700,
    slidesToShow: 3,
    slidesToScroll: 3,
};

export const settings4 = {
    dots: true,
    infinite: true,
    speed: 700,
    slidesToShow: 2,
    slidesToScroll: 2,
};

export const dataUsers = [
  { id: 1, username: 'johnDoe5678', email: 'johnDoe5678@gmail.com', phone: '+84912345678' },
  { id: 2, username: 'emmaNguyen09', email: 'emmaNguyen09@gmail.com', phone: '+84987654321' },
  { id: 3, username: 'khoaTran123', email: 'khoaTran123@gmail.com', phone: '+84876543219' },
  { id: 4, username: 'sophieLe987', email: 'sophieLe987@gmail.com', phone: '+84956473829' },
  { id: 5, username: 'jackPham450', email: 'jackPham450@gmail.com', phone: '+84839475029' },
  { id: 6, username: 'annaVu2000', email: 'annaVu2000@gmail.com', phone: '+84918273645' },
  { id: 7, username: 'lucasHoang75', email: 'lucasHoang75@gmail.com', phone: '+84839485764' },
  { id: 8, username: 'michaelNgo85', email: 'michaelNgo85@gmail.com', phone: '+84927483619' },
  { id: 9, username: 'juliaDo567', email: 'juliaDo567@gmail.com', phone: '+84856372819' },
  { id: 10, username: 'davidTran34', email: 'davidTran34@gmail.com', phone: '+84918273645' },
];

export const dataOrders = [
  {code: '#6104929598', totalPrice: 49718, date: '23/11/2024, 00:52'},
  {code: '#7887604585', totalPrice: 67134, date: '19/11/2024, 22:39'},
  {code: '#7173090385', totalPrice: 75215, date: '21/11/2024, 22:48'},
  {code: '#4624410364', totalPrice: 18268, date: '28/11/2024, 08:01'},
  {code: '#2866571203', totalPrice: 38194, date: '25/11/2024, 10:22'},
  {code: '#1619303371', totalPrice: 70483, date: '28/11/2024, 13:59'},
  {code: '#1931052205', totalPrice: 16201, date: '25/11/2024, 10:41'},
  {code: '#7380310145', totalPrice: 66086, date: '24/11/2024, 23:04'},
  {code: '#5125614867', totalPrice: 42967, date: '24/11/2024, 01:05'},
  {code: '#3822078725', totalPrice: 29474, date: '27/11/2024, 05:36'}
]